version: '2.2'

services:
  data:
    image: alpine:3.4
    volumes:
      - .:/var/www/html
      - /var/www/html/var/

  composer:
    image: composer:1.4
    command: 'install --prefer-dist --no-suggest --optimize-autoloader --no-interaction --ignore-platform-reqs'
    working_dir: /var/www/html
    volumes_from:
      - data
    healthcheck:
      test: ['CMD-SHELL', 'test -f vendor/autoload.php']
      interval: 10s
      timeout: 5s
      retries: 30

  database:
    image: mysql:5.5
    volumes_from:
      - data
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
      - MYSQL_DATABASE=symfony
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: '/usr/local/mysql/bin/mysqladmin --user=user --password=user ping'
      interval: 30s
      timeout: 10s
      retries:  10
    ports:
      - 3306
    networks:
      - symfony-net

  php:
    image: sf/php:7.1
    working_dir: /var/www/html
    volumes_from:
      - data
    depends_on:
      composer: { condition: service_healthy }
      database: { condition: service_healthy }
    environment:
      - PATH=/var/www/html/vendor/bin:$PATH
      - DATABASE_URL=mysql://user:user@database:3306/symfony
      - SYMFONY_DEBUG=0
      - SYMFONY_ENV=test
    networks:
      - symfony-net

networks:
  symfony-net:
    driver: bridge
